<?php

namespace AppBundle\Repository;

/**
 * RequeteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequeteRepository extends \Doctrine\ORM\EntityRepository
{
    function getPlaintes() {
        $results = array();
        $em = $this->getEntityManager();
        $query = $em->createQuery(
        'SELECT p
        FROM AppBundle:Requete p
        ORDER BY p.date DESC');

        $plaintes = $query->getResult();
        
        foreach ($plaintes as $val) {
        $id_plainte = $val->getId();
        $date = $val->getDate()->format('d/m/Y');
        $sujet = $val->getSujet();
        $message = $val->getMessage();
        $user_id = $val->getUser();
        $query = $em->createQuery(
        'SELECT u
        FROM AppBundle:User u
        WHERE u.id = :id')->setParameter('id', $user_id);
        $user = $query->getResult();
        $nom = $user[0]->getNom() . ' ' . $user[0]->getPrenom();
        $results[] = array("id" => $id_plainte, "date" => $date, "object" => $sujet, "message" => $message, "user" => $nom); 
        }
        
        return $results;
    }
    
    function deletePlaintes($id_message) {
        $em = $this->getEntityManager();
        $line = $em->getRepository('AppBundle:Requete')->find($id_message);
        $em->remove($line);
        $em->flush();
    }
}