AppBundle\Entity\Description:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\DescriptionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        description_accueil:
            type: string