AppBundle\Entity\Requete:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\RequeteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        sujet:
            type: string
            length: 255
        message:
            type: text
        date:
            type: datetime
    manyToOne:
        statut:
          targetEntity: Statut
          joinColumn:
            name: statut_id
            referencedColumnName: id
        type:
            targetEntity: TypeMessage
            joinColumn:
              name: type_id
              referencedColumnName: id
        user:
          targetEntity: User
          joinColumn:
            name: user_id
            referencedColumnName: id
    lifecycleCallbacks: {  }
